import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import FooterPage from "./components/footer";
import WorkoutProvider from "./context/workoutContext";
import { ToastContainer } from "react-toastify";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "FitLog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col container mx-auto">
        <WorkoutProvider>
        <Navbar></Navbar>
        
        <div className="bg-base-200">
          {children}
        </div>
          <FooterPage></FooterPage>
          </WorkoutProvider>
        <ToastContainer />
        </body>
    </html>
  );
}
